version: '3.7'
services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pw4root
      POSTGRES_DB: ticketless
    ports:
      - 5432:5432
    volumes:
      - $PWD/volumes/sql/postgres:/var/lib/postgresql/data
      - $PWD/configuration/sql/postgres-config:/docker-entrypoint-initdb.d

  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - $PWD/volumes/sql/mysql:/var/lib/mysql
      - $PWD/configuration/sql/mysql-config:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=pw4root
    ports:
      - 3306:3306

  db-admin:
    image: adminer
    restart: always
    ports:
      - 9090:8080    
